### ISSUE TITLE
Tic Tac Toe - Code Review 

### ISSUE THREAD

**Issue by peonicles** [peonicles/wdi-sg-playground#1]
@cbas @sevresbabylone, my tic tac toe work is located at `game_tic-tac-toe/`

**Comment by cbas** [comment]
:+1: Very nice and clean code. I like it.

Suggestions:
- Tidy up by removing the `console.log` debug messages.
- Eliminate the global variables `winner` and `draw`. Instead, return a Boolean (`true`/`false`) from `checkWin` and `checkDraw`. Keep the `window.alert` calls within the main event loop.
- Use `removeEventListener` to break the event loop. (This eliminates the need for `if (winner || draw) return`.)

**Comment by peonicles** [comment]
Moved the tic tac toe game to its own repository.
